name: CMake on Multiple Platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure feedback for all matrix combinations
      fail-fast: false

      # Matrix for 3 configurations:
      # 1. Windows with MSVC (cl)
      # 2. Ubuntu with GCC (g++)
      # 3. Ubuntu with Clang (clang++)
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Setup MSVC (Windows only)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.40  # Matches VS 2022 default as of March 2025; adjust to your local MSVC version if needed

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Run Executable
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: bash
      run: |
        # Set executable name based on OS
        executable="StructofArr_vs_ArrofStruct"  # Adjust this if your executable name differs
        
        if [ "$RUNNER_OS" == "Windows" ]; then
          executable="${executable}.exe"
          executable_path="${{ github.workspace }}\\build\\${{ matrix.build_type }}\\$executable"
        else
          executable_path="${{ github.workspace }}/build/$executable"
        fi
        
        # Check if the executable exists
        echo "Checking if executable exists: $executable_path"
        if [ -f "$executable_path" ]; then
          echo "Executable found, running it with args"
          # Run with explicit size and iterations for consistency and reduced noise
          "$executable_path" --size 100000 --iterations 10000
        else
          echo "Executable not found: $executable_path"
          exit 1
        fi
